{"name": "test_type_error", "status": "broken", "statusDetails": {"message": "TypeError: can only concatenate str (not \"int\") to str", "trace": "self = <test_example.TestExampleError testMethod=test_type_error>\n\n    def test_type_error(self):\n        \"\"\"Test qui génère une erreur de type.\"\"\"\n>       return \"string\" + 1\nE       TypeError: can only concatenate str (not \"int\") to str\n\nexamples\\test_example.py:55: TypeError"}, "description": "Test qui génère une erreur de type.", "start": 1744388741203, "stop": 1744388741204, "uuid": "3b5213e0-8d1c-4ee6-b29f-2a599009f427", "historyId": "5b9f015da0df617337cc2b0914697f69", "testCaseId": "5b9f015da0df617337cc2b0914697f69", "fullName": "examples.test_example.TestExampleError#test_type_error", "labels": [{"name": "parentSuite", "value": "examples"}, {"name": "suite", "value": "test_example"}, {"name": "subSuite", "value": "TestExampleError"}, {"name": "host", "value": "DESKTOP-ORG3GN0"}, {"name": "thread", "value": "18216-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "examples.test_example"}]}